### ISSUE TITLE
Decide upon how will we schedule releases of the specification

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustainableweb-ig#5]
The existing CG structure follows upon the principle of:

- An "Unstable Channel" (otherwise known as a Living Specification) where alterations to the specification are made immediate and visible (this was provided as a much requested feature from contributors who wanted to see the results of their efforts).
- A "Stable Channel" (otherwise known as Snapshot Releases) where versioned editions of the specification were made public once a threshold was reached that contained "enough meaningful" or urgent updates to warrant a new edition of the document.

We could choose to continue this model if IG members are happy as this model has worked well for us previously, and it meets the brief of the charter in providing us with the option of stable versioned releases (for the purposes of notes and statements) while having the immediacy of offering a Living Specification for readers wanting the latest cutting edge knowledge.

If this option is not useful, other release mechanisms can be offered for feedback and concensus.

**Comment by ldevernay** [comment]
This model sounds good to me.

**Comment by AlexDawsonUK** [comment]
**Note:** Regarding the structure, we have the option of either having the drafts within a subdirectory of the WSG repo (to reduce the amount of extra repositories we have to maintain, or we could have a wsg-drafts repo for any living document / edit in the open ReSpec files prior to any snapshot releases being ported to the WSG repo for public release at a scheduled timeframe (both options are easy to work with, its just a file management decision).

**Comment by AlexDawsonUK** [comment]
We have made the decision to go with a living document and to follow a single release track (to ensure new features reach the public as quickly as possible). Snapshots can be provided as and when we reach stable Note / Statement stages later in the development track as we reach greater stability. This issue can be considered closed.
