### ISSUE TITLE
supplemental documents

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/sustainableweb-ig#9]
Discuss plans for supplemental materials from CG

STAR: https://w3c.github.io/sustyweb/star.html
At A Glance: https://w3c.github.io/sustyweb/glance.html
Introduction: https://w3c.github.io/sustyweb/intro.html
Laws & Policies: https://w3c.github.io/sustyweb/policies.html
Quick Reference: https://w3c.github.io/sustyweb/quickref.html

**Comment by AlexDawsonUK** [comment]
This also applies to any educational materials we may create.

**Comment by AlexDawsonUK** [comment]
**Note:** Regarding the structure of the repository, we can either hold all of the supplements within the same repository as the main specification (for ease of editing), or we can separate concerns and have supplements and API within their own dedicated repositories (whatever works best for the group is what we shall use).

**Comment by TzviyaSiegman** [comment]
@ldevernay Alex granted your wish 😄. See https://github.com/w3c/sustainableweb-wsg. We will add to the readme to clarify the exact structure.

**Comment by AlexDawsonUK** [comment]
Transition is still ongoing so avoid making any changes to the docs until I've finished all the necessary internal tweaks (I'll be confirming here on the GitHub issues. But you can see the changes as they take place ([this will be our new GH pages URL](https://w3c.github.io/sustainableweb-wsg/)).

**Comment by AlexDawsonUK** [comment]
For ease of editing, we have decided to maintain all of the documents within a single repository.
Documentation on contribution and our processes will be upcoming in due course.
The transition process is now considered complete, so this issue can be marked as resolved.
